# spring 2.4 버전부터 profiles 선언 방식이 변경됨
# spring.profiles.active임을 주의하자!
# 그리고 구분자 및 spring.config.activate.on-profile로 설정을 구분할 수 있다.
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.87:3306/community?useSSL=true&verifyServerCertificate=true&allowPublicKeyRetrieval=true&&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: Community
    password: community
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
---
#Spring security를 본격 구현하기 전 테스트 로그인 계정
  messages:
    basename: message/messages,errors

logging:
  level:
    root: info
    org:
      hibernate.SQL: info
    # hibernate.type: trace
      springframework: error

jwt.secretKey: "47edd4a2-8555-4078-9b53-b652e11fc5dd"